### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by sudhan77** [collective/collective.registrationcaptcha#1]
is collective.registrationcaptcha to be installed via buildout. I tried. it does not come into the addon. I am using plone 4.3. pls advise any workable add-on process

**Comment by petschki** [comment]
hi, please check out the plone documentation pages here http://docs.plone.org/adapt-and-extend/install_add_ons.html . if there is something you miss, feel free to ask for help http://docs.plone.org/askforhelp.html .

**Comment by sudhan77** [comment]
hi petschki, I am using the documentation used there. i do not get any errors but the addon does not reflect in the addon section of the plone site. i tried using pip.

i ended with following error msg.

Downloading/unpacking z3c.zcmlhook (from plone.supermodel>=1.1dev->plone.app.registry->plone.app.discussion->collective.registrationcaptcha)
  Could not find a version that satisfies the requirement z3c.zcmlhook (from plone.supermodel>=1.1dev->plone.app.registry->plone.app.discussion->collective.registrationcaptcha) (from versions: 1.0b1)
  Some externally hosted files were ignored (use --allow-external to allow).
Cleaning up...
No distributions matching the version for z3c.zcmlhook (from plone.supermodel>=1.1dev->plone.app.registry->plone.app.discussion->collective.registrationcaptcha)
Storing debug log for failure in /root/.pip/pip.log
